# Generated by Django 3.2 on 2022-03-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('document', models.FileField(upload_to='scripts/', verbose_name='Document')),
            ],
            options={
                'verbose_name_plural': ' PanelDocument',
            },
        ),
        migrations.CreateModel(
            name='PanelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_no', models.CharField(blank=True, help_text='Panel Number', max_length=50, null=True, verbose_name='Panel Number')),
                ('installed_date_str', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Installed Date')),
                ('retirement_date_str', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Retirement Date')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Installed Date')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Retirement Date')),
                ('market_name', models.CharField(blank=True, help_text='Market Name', max_length=100, null=True, verbose_name='Market Name')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('status', models.CharField(blank=True, help_text='Status', max_length=50, null=True, verbose_name='Status')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('address_title', models.CharField(blank=True, max_length=40, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('office', 'Office'), ('personal', 'Personal'), ('Other', 'Other'), ('current', 'Current'), ('permanent', 'Permanent')], max_length=40, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '    Panel Master',
            },
        ),
        migrations.CreateModel(
            name='PanelPlayerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_no', models.CharField(blank=True, help_text='Panel Number', max_length=50, null=True, verbose_name='Panel Number')),
                ('installed_date_str', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Installed Date')),
                ('retirement_date_str', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Retirement Date')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Installed Date')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Retirement Date')),
                ('code', models.CharField(blank=True, help_text='Code Number', max_length=50, null=True, verbose_name='Code')),
                ('player_no', models.CharField(blank=True, help_text='Player Number', max_length=50, null=True, verbose_name='Player Number')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('wk4_imp', models.CharField(blank=True, max_length=100, null=True, verbose_name='4 Week Impressions')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size')),
                ('submarket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Submarket')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('sales_spot', models.CharField(blank=True, help_text='Sales Spot', max_length=100, null=True, verbose_name='Sales Spot')),
            ],
            options={
                'verbose_name_plural': '    Panel Player Details',
            },
        ),
        migrations.CreateModel(
            name='PanelStaticDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_no', models.CharField(blank=True, help_text='Panel Number', max_length=50, null=True, verbose_name='Panel Number')),
                ('installed_date_str', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Installed Date')),
                ('retirement_date_str', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Retirement Date')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Installed Date')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Retirement Date')),
                ('code', models.CharField(blank=True, help_text='Code Number', max_length=50, null=True, verbose_name='Code')),
                ('player_no', models.CharField(blank=True, help_text='Player Number', max_length=50, null=True, verbose_name='Player Number')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('wk4_imp', models.CharField(blank=True, max_length=100, null=True, verbose_name='4 Week Impressions')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size')),
                ('submarket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Submarket')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('media_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Media Type')),
                ('unit_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Type')),
            ],
            options={
                'verbose_name_plural': '    Panel Static Details',
            },
        ),
    ]
