# Generated by Django 3.2 on 2022-03-28 10:37

import calc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('directory_name', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Directory')),
                ('calculator_seq_no', models.CharField(default=calc.models.increment_calculator_seq_no, editable=False, max_length=20)),
                ('active', models.BooleanField(default=True, editable=False, verbose_name='Active')),
                ('is_published', models.BooleanField(default=True, editable=False, verbose_name='Is Published')),
            ],
            options={
                'verbose_name_plural': '   Calculator Master',
                'db_table': 'calculator_master',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Currency Code', max_length=10, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(blank=True, help_text='Currency Name', max_length=100, unique=True, verbose_name='Currency Name')),
            ],
            options={
                'verbose_name_plural': '     Currency Master',
                'db_table': 'currency_master',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('document', models.FileField(upload_to=calc.models.get_upload_to, verbose_name='Document')),
                ('is_auto', models.BooleanField(default=False, editable=False, verbose_name='Is Auto')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('export_csv', 'Export CSV'), ('import_journal', 'Import Journal')], default='draft', max_length=20, null=True, verbose_name='Status')),
                ('calculator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_id', to='calc.calculatormaster', verbose_name='Tag Calculator')),
            ],
            options={
                'verbose_name_plural': ' Document',
                'db_table': 'document_master',
            },
        ),
        migrations.CreateModel(
            name='RateAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_perc', models.FloatField(blank=True, null=True, verbose_name='Filter Percentage')),
                ('society_approval_rate_perc', models.FloatField(blank=True, null=True, verbose_name='Society Approval Rate (%)')),
                ('avg_price_change_perc', models.FloatField(blank=True, null=True, verbose_name='Average Price Change (%)')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending for Approval'), ('approve', 'Approved'), ('reject', 'Rejected'), ('cancel', 'Cancelled')], default=None, max_length=20, null=True, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Approve/Reject Remarks')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate_analysis_no', models.CharField(default=calc.models.increment_rate_analysis_number, editable=False, max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('calculator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_calculator_id', to='calc.calculatormaster', verbose_name='Calculator')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_document_id', to='calc.document', verbose_name='Reference Document')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited by')),
            ],
            options={
                'verbose_name_plural': '     Rate Analysis',
                'db_table': 'calc_rate_analysis',
            },
        ),
        migrations.CreateModel(
            name='ScenarioMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Scenario Name', max_length=100, unique=True, verbose_name='Scenario Name')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': '     Scenario Master',
                'db_table': 'scenario_master',
            },
        ),
        migrations.CreateModel(
            name='RateAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_perc', models.FloatField(blank=True, null=True, verbose_name='Filter Percentage')),
                ('society_approval_rate_perc', models.FloatField(blank=True, null=True, verbose_name='Society Approval Rate (%)')),
                ('avg_price_change_perc', models.FloatField(blank=True, null=True, verbose_name='Average Price Change (%)')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending for Approval'), ('approve', 'Approved'), ('reject', 'Rejected'), ('cancel', 'Cancelled')], default=None, max_length=20, null=True, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Approve/Reject Remarks')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, choices=[('modify', 'Modified')], max_length=20, null=True, verbose_name='Action')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('rate_analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_analysis_id', to='calc.rateanalysis', verbose_name='Analysis')),
            ],
            options={
                'verbose_name_plural': '     Rate Analysis History',
                'db_table': 'calc_rate_analysis_history',
            },
        ),
        migrations.CreateModel(
            name='RateAnalysisDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_structure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ownership Structure')),
                ('apc_change_perc', models.CharField(blank=True, max_length=10, null=True, verbose_name='APC Change (%)')),
                ('journal_count', models.FloatField(blank=True, null=True, verbose_name='Number of Journal')),
                ('revenue_change', models.FloatField(blank=True, null=True, verbose_name='Revenue Change')),
                ('rate_analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_line_id', to='calc.rateanalysis', verbose_name='Analysis')),
            ],
            options={
                'verbose_name_plural': '     Rate Analysis Details',
                'db_table': 'calc_rate_analysis_line',
            },
        ),
        migrations.AddField(
            model_name='rateanalysis',
            name='scenario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_scenario_id', to='calc.scenariomaster', verbose_name='Scenario'),
        ),
        migrations.AddField(
            model_name='rateanalysis',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileid', models.AutoField(primary_key=True, serialize=False)),
                ('calculator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculator_id', to='calc.calculatormaster', verbose_name='Tag Calculator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': '      Profile',
            },
        ),
        migrations.CreateModel(
            name='JournalMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Journal Code')),
                ('name', models.CharField(max_length=100, verbose_name='Journal Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('calculator_ids', models.ManyToManyField(to='calc.CalculatorMaster', verbose_name='Tag Calculator')),
            ],
            options={
                'verbose_name_plural': '  Journal Master',
                'db_table': 'journal_master',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='scenario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_id', to='calc.scenariomaster', verbose_name='Tag Scenario'),
        ),
        migrations.CreateModel(
            name='CurrencyRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Conversion Code', max_length=10, unique=True, verbose_name='Conversion Code')),
                ('name', models.CharField(blank=True, help_text='Conversion Name', max_length=100, unique=True, verbose_name='Conversion Name')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('conversion_rate', models.FloatField(verbose_name='Conversion Rate')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='calc.currencymaster', verbose_name='From Currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='calc.currencymaster', verbose_name='To Currency')),
            ],
            options={
                'verbose_name_plural': '    Currency Rate Master',
                'db_table': 'currency_rate_master',
                'ordering': ['-effective_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='calculatormaster',
            name='currency_ids',
            field=models.ManyToManyField(blank=True, related_name='currency_ids', to='calc.CurrencyMaster', verbose_name='Secondary Currency'),
        ),
        migrations.AddField(
            model_name='calculatormaster',
            name='primary_currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_currency_id', to='calc.currencymaster', verbose_name='Primary Currency'),
        ),
    ]
