# Generated by Django 3.2 on 2022-02-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('directory_name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('is_published', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Calculator Master',
                'db_table': 'calculator_master',
            },
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Currency Master',
                'db_table': 'currency_master',
            },
        ),
        migrations.CreateModel(
            name='JournalMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('calc_ids', models.ManyToManyField(to='calc.CalculatorMaster')),
            ],
            options={
                'verbose_name': 'Journal Master',
                'db_table': 'journal_master',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('conversion_rate', models.FloatField()),
                ('active', models.BooleanField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='calc.currencymaster')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='calc.currencymaster')),
            ],
            options={
                'verbose_name': 'Currency Rate Master',
                'db_table': 'currency_rate_master',
                'ordering': ['-effective_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='calculatormaster',
            name='currency_ids',
            field=models.ManyToManyField(to='calc.CurrencyMaster'),
        ),
        migrations.AddField(
            model_name='calculatormaster',
            name='primary_currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_currency_id', to='calc.currencymaster'),
        ),
    ]
