# Generated by Django 3.2 on 2022-03-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateanalysis',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
