# Generated by Django 3.2 on 2022-02-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calculator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_id', to='calc.calculatormaster'),
        ),
    ]
