# Generated by Django 3.2 on 2022-02-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20220226_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatormaster',
            name='currency_ids',
            field=models.ManyToManyField(related_name='currency_ids', to='calc.CurrencyMaster', verbose_name='Secondary Currency'),
        ),
    ]
