# Generated by Django 3.2 on 2022-02-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20220228_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatormaster',
            name='currency_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='currency_ids', to='calc.CurrencyMaster', verbose_name='Secondary Currency'),
        ),
        migrations.AlterField(
            model_name='document',
            name='calculator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_id', to='calc.calculatormaster', verbose_name='Tag Calculator'),
        ),
        migrations.AlterField(
            model_name='journalmaster',
            name='calculator_ids',
            field=models.ManyToManyField(to='calc.CalculatorMaster', verbose_name='Tag Calculator'),
        ),
    ]
