# Generated by Django 3.2 on 2022-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20220228_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Scenario Name', max_length=100, unique=True, verbose_name='Scenario Name')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': '     Scenario Master',
                'db_table': 'scenario_master',
            },
        ),
    ]
