# Generated by Django 3.2 on 2022-03-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_scenariomaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scenario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_id', to='calc.scenariomaster', verbose_name='Tag Scenario'),
        ),
    ]
