# Generated by Django 3.2 on 2022-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_document_scenario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatormaster',
            name='currency_ids',
            field=models.ManyToManyField(blank=True, related_name='currency_ids', to='calc.CurrencyMaster', verbose_name='Secondary Currency'),
        ),
    ]
