# Generated by Django 3.2 on 2022-03-09 06:56

import calc.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_alter_calculatormaster_currency_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_analysis_no', models.CharField(default=calc.models.increment_rate_analysis_number, editable=False, max_length=20)),
                ('filter_perc', models.FloatField(blank=True, null=True, verbose_name='Filter Percentage')),
                ('society_approval_rate_perc', models.FloatField(blank=True, null=True, verbose_name='Society Approval Rate (%)')),
                ('avg_price_change_perc', models.FloatField(blank=True, null=True, verbose_name='Average Price Change (%)')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending for Approval'), ('approve', 'Approved'), ('reject', 'Rejected'), ('cancel', 'Cancelled')], default=None, max_length=20, null=True, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Approve/Reject Remarks')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('calculator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_calculator_id', to='calc.calculatormaster', verbose_name='Calculator')),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_document_id', to='calc.document', verbose_name='Reference Document')),
                ('scenario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_scenario_id', to='calc.scenariomaster', verbose_name='Scenario')),
            ],
            options={
                'verbose_name_plural': '     Rate Analysis',
                'db_table': 'calc_rate_analysis',
            },
        ),
        migrations.CreateModel(
            name='RateAnalysisDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_structure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ownership Structure')),
                ('apc_change_perc', models.CharField(blank=True, max_length=10, null=True, verbose_name='APC Change (%)')),
                ('journal_count', models.FloatField(blank=True, null=True, verbose_name='Number of Journal')),
                ('revenue_change', models.FloatField(blank=True, null=True, verbose_name='Revenue Change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rate_analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_line_id', to='calc.rateanalysis', verbose_name='Analysis')),
            ],
            options={
                'verbose_name_plural': '     Rate Analysis Details',
                'db_table': 'calc_rate_analysis_line',
            },
        ),
    ]
