# Generated by Django 3.2 on 2022-03-10 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0011_rateanalysis_rateanalysisdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
