# Generated by Django 3.2 on 2022-03-11 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0012_rateanalysis_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateanalysisdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rateanalysisdetails',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='rateanalysis',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited by'),
        ),
        migrations.AddField(
            model_name='rateanalysis',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_analysis_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rateanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='rateanalysis',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='RateAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_perc', models.FloatField(blank=True, null=True, verbose_name='Filter Percentage')),
                ('society_approval_rate_perc', models.FloatField(blank=True, null=True, verbose_name='Society Approval Rate (%)')),
                ('avg_price_change_perc', models.FloatField(blank=True, null=True, verbose_name='Average Price Change (%)')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending for Approval'), ('approve', 'Approved'), ('reject', 'Rejected'), ('cancel', 'Cancelled')], default=None, max_length=20, null=True, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Approve/Reject Remarks')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, choices=[('modify', 'Modified')], max_length=20, null=True, verbose_name='Action')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('rate_analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_analysis_id', to='calc.rateanalysis', verbose_name='Analysis')),
            ],
            options={
                'verbose_name_plural': '     Rate Analysis History',
                'db_table': 'calc_rate_analysis_history',
            },
        ),
    ]
